# Generated by Django 3.1.5 on 2021-05-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210516_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
                ('content', models.TextField()),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.accountuser')),
            ],
        ),
    ]
