# Generated by Django 3.1.5 on 2021-06-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
