# Generated by Django 3.1.5 on 2021-06-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_accountuser_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountuser',
            name='video',
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='images'),
        ),
    ]
